erDiagram
    flySelskaber{
        _ navn
    } 
    fly  {
        _ navn
        _ model
        _ nummer
    }

    flySæder{
        _ nummer
        _ type
    }

    rejse{
        _ fraLufthavn
        _ fraTidspunkt
        _ tilLufthavn
        _ tilTidspunkt
        _ bestemtFly
    }


    booking{
        _ person
        _ rejse
        _ pris
    }

    personer{
        _ fornavn
        _ efternavn
    }

    lufthavn{
        _ location
        _ navn
    }
